@api= http://localhost:5000

GET {{api}}/videos

###
GET {{api}}/videos/60208859b1b9b775e846881f
###
POST {{api}}/videos
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=DWKUEPqLn3k",
    "title": "La gran belleza",
    "description": "Italian film"

}
###
DELETE {{api}}/videos/1

###
PUT {{api}}/videos/1
